### ISSUE TITLE
Add support for VMRay sandbox results for capa dynamic analysis

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#2148]
We're working on adding support to parse VMRay result files for capa dynamic processing.

To add this functionality tasks include:
- identify relevant VMRay files, so far `flog.xml` and `summary_v2.json`
- add the respective pydantic models to parse relevant data
- add a VMRayExtractor
  - add base extractor
  - add scope extractors
```[tasklist]
### Tasks
- [x] undo formatting changes / apply correct lints/formatting
- [x] complete extractor.py implementation analogous to CAPE (almost done)
- [x] complete/cleanup call.py
- [x] complete/cleanup file.py
- [x] complete global.py
- [x] add process.py - get_threads(?)
- [x] complete/cleanup models.py
- [x] add test archives - clarify if/how can publish
- [x] add tests/test_vmray_models.py to test VMRay models
- [x] add tests/test_vmray_features.py to test feature presence and counts
```

**Comment by mike-hunhoff** [comment]
The source file appears to be stored under `<archive>/internal/static_anlayses/<sha256>/objects/files/<sha256>`. We'll need to reference the source file to emit `string` features at the file scope as this information doesn't appear to be stored elsewhere

**Comment by mike-hunhoff** [comment]
The VMRay analysis archive contains memory dumps for all monitored processes. We should consider emitting features, e.g. `string`,  from all or a subset of these memory dumps to help detect capabilities. Performance may be an issue here as VMRay generates MANY memory dumps during execution and most appear to be junk. We may be able to narrow our focus to the initial process created for the target sample, although we could be missing interesting data in the child processes.

**Comment by mr-tz** [comment]
closed via #2208

**Comment by mr-tz** [comment]
> The VMRay analysis archive contains memory dumps for all monitored processes. We should consider emitting features, e.g. `string`, from all or a subset of these memory dumps to help detect capabilities. Performance may be an issue here as VMRay generates MANY memory dumps during execution and most appear to be junk. We may be able to narrow our focus to the initial process created for the target sample, although we could be missing interesting data in the child processes.

@mike-hunhoff should we track this separately?
