### ISSUE TITLE
performance issues with some samples (July 2024)

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#2225]
Investigate CPU and memory usage for the following samples. If it's something we're doing wrong, let's optimize that behavior. If its an issue with viv or other dependency, perhaps we can introduce heuristics to detect difficult samples and bail early (opt-in).

```[tasklist]
### Tasks
  - [ ] 0818ba016a7de9c85ff8426378816c507fddb17440f5636f7f90e9a8c087804d
  - [ ] 0bbb439a8cbd293da7f5f8c83077f8dfa01f42a919d582ec169b596e0d3f43c2
  - [ ] 0fc9badf046c3b4336cdbd7982f693125be1df4b9cce0db469a74ef175466b70
  - [ ] 18af52e695c2c1075052e2ff72efc984739049858e3e10f389bb2ce6837d8b3d
  - [ ] 1fcc2f0a74cb605fd3884328ce08c0591a084e024f5877300439f955eca80154
```

**Comment by williballenthin** [comment]
# 0818ba016a7de9c85ff8426378816c507fddb17440f5636f7f90e9a8c087804d

Its big:
![image](https://github.com/user-attachments/assets/46b9896f-b70a-444e-a320-432df66f030e)

![image](https://github.com/user-attachments/assets/d0b7fb80-1176-4529-91ab-cf58965a830c)
![image](https://github.com/user-attachments/assets/c41760d6-504a-41e8-be2a-2326e9b03247)

**Comment by williballenthin** [comment]
# 0bbb439a8cbd293da7f5f8c83077f8dfa01f42a919d582ec169b596e0d3f43c2

BN:
![image](https://github.com/user-attachments/assets/82f0daa3-ba80-4295-84ef-c62204ee8cd8)

![image](https://github.com/user-attachments/assets/6638d3fa-e244-4709-9d2d-50d853f405e0)

**Comment by williballenthin** [comment]
# 0fc9badf046c3b4336cdbd7982f693125be1df4b9cce0db469a74ef175466b70
.NET

takes 44s

**Comment by williballenthin** [comment]
# 18af52e695c2c1075052e2ff72efc984739049858e3e10f389bb2ce6837d8b3d

packed

8s

**Comment by williballenthin** [comment]
# 1fcc2f0a74cb605fd3884328ce08c0591a084e024f5877300439f955eca80154

embedded PE

6s

**Comment by williballenthin** [comment]
these samples seem to be erroneously recorded
