### ISSUE TITLE
web: add landing page for capa

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#2261]
to be loaded at: https://mandiant.github.io/capa/
```[tasklist]
### Tasks
- [ ] draft content (pull from index.md?)
- [ ] move capa explorer web to /capa/explorer/
- [ ] update gh action to push the landing page to gh pages
```
