### ISSUE TITLE
plan: rule reorganization

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#23]
- [x] agree on proposed rule names and namespaces. see shared excel spreadsheet.
  - [x] develop script to do migration #25
  - [x] develop formatter to ensure consistency of formatted rules #8
  - [x] run formatter on all rules (and confirm results) https://github.com/fireeye/capa-rules/pull/12
  - [x] execute migration https://github.com/fireeye/capa-rules/pull/14
  - [x] post snapshot of excel spreadsheet https://github.com/fireeye/capa-rules/pull/14
  - [x] run formatter on all rules
  - [x] update linter to support namespaces
  - [x] document rule naming and namespacing conventions
  - [x] update outputter to support namespaces #34
  - [x] update readme with new rules and output examples
  - [x] update ida plugin to support namespaces @mike-hunhoff #58
  - [ ] update readme with screenshots of IDA plugin @mike-hunhoff #66 
  - [ ] update FC service to support namespaces @MalwareMechanic
