### ISSUE TITLE
detect and use third-party analysis backends when possible

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#2376]
capa has analysis backends for third party tools, like IDA, Binary Ninja, and Ghidra. It's possible to invoke capa to use these backends, but you typically have to be an expert to figure out how to do this.

We should investigate whether the standalone capa.exe can automatically detect installations of relevant third party applications and use their backends, when possible. For example, capa.exe could recognize that IDA is installed, figure out where the path is, and try to initialize idalib from that path. Of course, there are a lot of edge cases and possibilities, but I suspect a few common workflows might be achievable. For example, ensuring capa.exe in FLARE-VM uses the best available backend. Worst case, capa.exe continues to use the embedded vivisect backend.
```[tasklist]
### Tasks
- [x] IDA 9.0 idalib on Linux
- [ ] IDA 9.0 idalib on Windows
- [x] Binary Ninja on Linux
- [ ] Binary Ninja on Windows
- [ ] Binary Ninja on macOS
- [ ] IDA 9.0 idalib on macOS
```

**Comment by williballenthin** [comment]
### Binary Ninja on Linux

Installs an [XDG Desktop Entry](https://wiki.archlinux.org/title/Desktop_entries) like this:

```
❯ bat ~/.local/share/applications/com.vector35.binaryninja.desktop -p
[Desktop Entry]
Name=Binary Ninja
Exec=/home/wballenthin/software/binaryninja/binaryninja %u
MimeType=application/x-binaryninja;x-scheme-handler/binaryninja;
Icon=/home/wballenthin/software/binaryninja/docs/img/logo.png
Terminal=false
Type=Application
Categories=Utility;
Comment=Binary Ninja: A Reverse Engineering Platform
```

from which we can parse `Exec=/home/wballenthin/software/binaryninja/` to recover the spot where the binaryninja API is loaded.

**Comment by williballenthin** [comment]
### IDA on Linux

Also uses a Desktop Entry:

```
❯ bat -p /usr/share/applications/ida64.desktop
[Desktop Entry]
Name=IDA Pro (64-bit targets)
Exec=/opt/idapro/ida64
Icon=/opt/idapro/appico64.png
Terminal=false
Type=Application
StartupWMClass=ida64
```

and the IDA 9.0 idalib installation has a similar script to update the Python environment so that the shared libraries can be loaded. We can pull some of that logic into capa once the base directory is recovered.

**Comment by williballenthin** [comment]
### Windows

I think we can walk the registry to find where IDA/BinaryNinja are installed. Will update here when I try to make it work.

**Comment by williballenthin** [comment]
### macOS

I don't know and I don't have a system to test on. But maybe we can get outside contributors to help out. Alternatively, its OK because we can fallback to viv when necessary.

**Comment by williballenthin** [comment]
https://github.com/mandiant/capa/compare/push-lsvlznlppuyr

**Comment by williballenthin** [comment]
![image](https://github.com/user-attachments/assets/6cba19b0-d6a4-4244-b91d-436fa346ed97)

**Comment by williballenthin** [comment]
search for Binary Ninja API via XDG Desktop Entries in https://github.com/mandiant/capa/compare/push-ltqsxxylmzpy
